# Curator configuration
# https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html

client:
  hosts:
    - elasticsearch
  port: 9200
  http_auth: elastic:Hard2Translate!

logging:
  loglevel: INFO
  logformat: default
